[tool.black]
target-version = ["py311", "py312"]
line-length = 120

[tool.isort]
profile = "black"

[tool.pylint.'FORMAT']
max-line-length=120

[tool.pylint.'MESSAGES CONTROL']
disable = ["missing-module-docstring"]
